language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t heyser/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true heyser/docker-react npm run test
