language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t heyser/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heyser/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-412775748200"
  bucket_path: "docker"
  on:
    branch: master
   access_key_id: $AWS_Access_Key
   secret_acess_key: $AWS_SECRET_KEY
